// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgr1WFSMD3rasvKrJf9WCVTozKgTkncgI',
    appId: '1:457091133693:android:d15d268164799f81648e94',
    messagingSenderId: '457091133693',
    projectId: 'hook-353419',
    databaseURL: 'https://hook-353419-default-rtdb.firebaseio.com',
    storageBucket: 'hook-353419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwN5usgcLCcC1vzWdmi4B6Jkr8JK59iok',
    appId: '1:457091133693:ios:efa5ed1382af5c75648e94',
    messagingSenderId: '457091133693',
    projectId: 'hook-353419',
    databaseURL: 'https://hook-353419-default-rtdb.firebaseio.com',
    storageBucket: 'hook-353419.appspot.com',
    iosClientId: '457091133693-9n8in713m9qilnjs2j87kfual6uib3is.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicacionPrueba',
  );
}
